{% set name = "python-nvd3" %}
{% set version = "0.15.0" %}
{% set sha256 = "fbd75ff47e0ef255b4aa4f3a8b10dc8b4024aa5a9a7abed5b2406bd3cb817715" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

  entry_points:
    - nvd3 = nvd3.NVD3Chart:_main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-slugify >=1.1.4,<2
    - jinja2 >=2.8

test:
  imports:
    - nvd3
  commands:
    - nvd3 --help

about:
  home: http://github.com/areski/python-nvd3
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python NVD3 - Chart Library for d3.js'

  description: |
      NVD3 is an attempt to build re-usable charts and chart components
      for d3.js without taking away the power that d3.js offers you.
      Python-NVD3 makes your life easy! You write Python and the library
      renders JavaScript for you!
  doc_url: http://python-nvd3.readthedocs.io/en/latest
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - sodre
